export const menuItems = [
   { title: "Dashboard", path: "/dashboard" },
   {title:"WhatsApp",icon:"FaWhatsapp",items:["WhatsApp"]},
  { title: "Front Office", icon: "FaBuilding", items: ["Admission Enquiry", "Visitor Book", "Phone Call Log", "Postal Dispatch", "Postal Receive", "Complain", "Setup Front Office"] },
  { title: "Student Information", icon: "FaUserGraduate", items: ["Student Details", "Student Admission", "Online Admission", "Disabled Student", "Multi Class Student", "Bulk Delete", { name: "Student Categories", path: "/student-categories" }, { name: "Student House", path: "/student-house" }, "Disable Reason"] },
  { title: "Fees Collection", icon: "FaMoneyBillWave", items: ["Collect Fees", "Offline Bank Payments", "Search Fees Payment", "Search Due Fees", "Fees Master", "Fees Group", "Fees Discount", "Fees Type", "Fees Carry Forward", "Fees Reminder"] },
  { title: "Income", icon: "FaChartLine", items: ["Add Income", "Search Income", "Income Head"] },
  { title: "Expenses", icon: "FaReceipt", items: ["Add Expense", "Search Expense", "Expense Head"] },
  { title: "Examination", icon: "FaClipboardList", items: ["Exam Group", "Exam Schedule", "Exam Result", "Design Admit Card", "Print Admit Card", "Design Marksheet", "Print Marksheet", "Marks Grade", "Marks Division"] },
  { title: "Attendance", icon: "FaCalendarCheck", items: ["Student Attendance", "Approve Leave", "Attendance By Date"] },
  { title: "Online Examination", icon: "FaGlobe", items: ["Online Exam", "Question Bank"] },
  { title: "Academics", icon: "FaBookOpen", items: ["Class Timetable", "Teachers Timetable", "Assign Class Teacher", "Promote Student", "Subject Group", "Subjects", "Class", "Sections"] },
  { title: "Lesson Plan", icon: "FaClipboard", items: ["COPY OLD LESSONS", "Manage Lesson Plan", "Manage Syllabus Status", "Lesson", "Topic"] },
  { title: "Human Resource", icon: "FaUsers", items: ["Staff Directory", "Staff Attendance", "Payroll", "Approve Leave Report", "Apply Leave", "Leave Type", "Teachers Ratings", "Department", "Designation", "Disabled Staff"] },
  { title: "Communication", icon: "FaBroadcastTower", items: ["Notice Board", "Send Email", "Send SMS", "Email/SMS Log", "Schedule Email/SMS Log", "Login Credentials Send", "Email Template", "SMS Template"] },
  { title: "Download Center", icon: "FaDownload", items: ["Content Type", "Content Share List", "Upload / Share Content", "Video Tutorial"] },
  { title: "Homework", icon: "FaFlask", items: ["Add Homework", "Daily Assignment"] },
  { title: "Library", icon: "FaBookOpen", items: ["Book List", "Issue - Return", "Add Student", "Add Staff Member"] },
  { title: "Inventory", icon: "FaBoxOpen", items: ["Issue Item", "Add Item Stock", "Add Item", "Item Category", "Item Supplier", "Item Store"] },
  { title: "Transport", icon: "FaCarSide", items: ["Fee Master", "Pickup Points", "Routes", "Vehicles", "Assign Vehicle", "Route Pickup Point", "Student Transport Fees"] },
  { title: "Hostel", icon:  "FaKey", items: ["Hostel Rooms", "Room Type", "Hostel"] },
  { title: "Certificate", icon: "FaCertificate", items: ["Student Certificate", "Generate Certificate", "Student ID Card", "Generate ID Card", "Staff ID Card", "Generate Staff Id Card"] },
  { title: "Front CMS", icon: "FaCogs", items: ["Gallery", "News", "Media Manager", "Pages", "Menus", "Banner Image"] },
  { title: "Alumni", icon: "FaUserGraduate", items: ["Manage Alumni", "Events"] },
  { title: "Reports", icon: "FaChartLine", items: ["Student Information", "Finance", "Attendance", "Examination", "Online Examination", "Lesson Plan", "Human Resource", "Homework", "Library", "Inventory", "Transport", "Hostel Report", "Alumni", "User Log", "Audit Trail Report"] },
  { title: "System Settings", icon: "FaTools", items: ["General Settings", "Session Settings", "Notification Settings", "SMS Settings", "Payment Methods", "Email Settings", "Print Header Footer", "Front CMS Settings", "Role Permission", "Backup Restore", "Languages", "Currency", "Users", "Addons", "Modules", "Custom Fields", "Captcha Settings", "System Fields", "Student Profile Update", "Admission", "File Types", "Sidebar Menu", "System Update"] },
];